# Generated by Django 2.1.7 on 2021-09-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaCallBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_request_id', models.CharField(max_length=50)),
                ('checkout_request_id', models.CharField(max_length=50)),
                ('response_code', models.CharField(max_length=50)),
                ('response_description', models.CharField(max_length=50)),
                ('customer_message', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'MpesaCallBack',
                'verbose_name_plural': 'MpesaCallBacks',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
