# Generated by Django 2.1.7 on 2021-09-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daraja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=50)),
                ('organization_balance', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'MpesaPayment',
                'verbose_name_plural': 'MpesaPayments',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
