# Generated by Django 2.1.7 on 2021-09-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesacallbackAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lnmonline',
            options={'managed': True, 'verbose_name': 'LNMOnline', 'verbose_name_plural': 'LNMOnlines'},
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='Amount',
            field=models.FloatField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='CheckoutRequestID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='MerchantRequestID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='MpesaReceiptNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='ResultCode',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='ResultDes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='TransactionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='lnmonline',
            table='',
        ),
    ]
